project:
  type: book

book:
  title: "Non-reversible Tempering for multimodal densities"
  subtitle: "CDT Summer Project Report"
  author: "Fernando A. Zepeda Herrera"
  date: "28 August 2022"
  chapters:
    - index.qmd
    - 01_goal.qmd
    - 02_tempering.qmd
    - 03_challenges.qmd
    - references.qmd
  search: true
  repo-url: https://github.com/fazepher/Tempering_Report
  downloads: [pdf]

bibliography: biblio_tempering_report.bib
csl: jrss.csl

knitr: 
  opts_knit: 
    cache.extra: rand_seed
    dev.args: list(bg = "transparent")

execute:
  cache: true
  freeze: auto
  
format:
  html:
    theme: [cosmo, custom_style.scss]
    echo: false
  pdf:
    documentclass: scrreprt
    fontsize: "10pt"
    linestretch: "1.25"
    margin-top: "0.75in"
    margin-left: "1in"
    margin-bottom: "1.15in"
    margin-right: "1in"
    echo: false




