project:
  type: book

book:
  title: "Non-reversible Tempering for multimodal densities"
  subtitle: "CDT Summer Project Report"
  author: "Fernando A. Zepeda Herrera"
  date: "28 September 2022"
  chapters:
    - index.qmd
    - 01_goal.qmd
  search: true
  repo-url: https://github.com/fazepher/Tempering_Report
  downloads: [pdf]

execute:
  cache: true
  
format:
  html:
    theme: cosmo
    echo: false
  pdf:
    documentclass: scrreprt
    fontsize: "12pt"
    echo: false




